# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'jaffle_shop'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"


# Configuring models
models:
  jaffle_shop:
    # Requires at least 1 'unique' and 1 'not_null' test across all models
    +meta:
      required_tests:
        unique: 1
        not_null: 1

    staging:
      +materialized: view

    marts:
      +materialized: table
      # Adds a requirement for at least 1 'relationships' test on marts models
      +meta:
        required_tests:
          unique: 1
          not_null: 1
          relationships: 1
dispatch:
  - macro_namespace: audit_helper
    search_order: ['audit_helper', 'dbt']